services:
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
      target: dev
    env_file:
      - ./client/.env.local
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: '${NEXT_PUBLIC_API_URL:-http://localhost:3000/api}'
      NEXT_TELEMETRY_DISABLED: '1'
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - server
